### ISSUE TITLE
The code in useage has something wrong

### ISSUE THREAD

**Issue by firstandsecond** [DHZS/tf-dropblock#1]
It is here.
b = drop_block(a, training)
when I use it to test,it cannot run.After I changed it as     b = drop_block(a, training=True)
The code could run.

**Comment by DHZS** [comment]
Hi @firstandsecond, can you give me more information, such as complete code and/or error messages?

**Comment by firstandsecond** [comment]
The complete code is here.
import numpy as np
import tensorflow as tf
from nets.dropblock import DropBlock

# only support `channels_last` data format
a = tf.placeholder(tf.float32, [None, 10, 10, 3])
keep_prob = tf.placeholder(tf.float32)
training = tf.placeholder(tf.bool)

drop_block = DropBlock(keep_prob=keep_prob, block_size=3)
b = drop_block(a, training)

sess = tf.Session()
feed_dict = {a: np.ones([2, 10, 10, 3]), keep_prob: 0.8, training: True}
c = sess.run(b, feed_dict=feed_dict)

print(c[0, :, :, 0])


when I  run this code it is failed, unless I change 
b = drop_block(a, training)
into 
b = drop_block(a, training=True)

**Comment by DHZS** [comment]
Maybe the problem was caused by the tensorflow version, I'm using tensorflow 1.12.0 and the code is working fine on my computer.
I wrote an example in Google Colab, you can check it out from here: https://colab.research.google.com/drive/18eOcpTLH4xXpa4B75I62JJSgM49CxkGF

**Comment by firstandsecond** [comment]
Maybe the problem is the tensorflow's version.My tensorflow's version is 1.2.1.
Thanks.
