### ISSUE TITLE
fix bug

### ISSUE THREAD

**Issue by bei-startdt** [DHZS/tf-dropblock#3]
mask = tf.cast(mask, tf.float32) should add before maxpooling if using for GPU training in tensorflow-gpu version 1.11, otherwise there will be some warning occur.

**Comment by DHZS** [comment]
Thank you for your bug report @bei-startdt. Actually, the variable `mask` is created by `tf.random_uniform()` in the function `_bernoulli()`, and the type of return value is defined by `dtype=tf.float32`.

I tested the code in tensorflow-gpu 1.11.0, it seems that the code is working fine. Could you give me more information about your code & output message?

**Comment by bei-startdt** [comment]
It's my fault. Close please.
